### ISSUE TITLE
About generate Monalisa Reenactment

### ISSUE THREAD

**Issue by kenoharada** [TArdelean/CainGAN#3]
Hi!
I ended training the model.

Then I try to generate new images in one-shot setting.

Has fine-tuning been done when you create monalisa images in the demo??

![スクリーンショット 2020-05-18 13 56 35](https://user-images.githubusercontent.com/26840538/82175695-8bf6fc00-990f-11ea-98df-9d3f9e605f2f.png)

And how did you select driving landmark for monalisa??

If you have tips for generate new images, could you share it??

Thanks

**Comment by TArdelean** [comment]
Hi!
No fine-tuning has been done for any of the generated images.
I searched for a person with similar landmarks in VoxCeleb2 and used that video for driving poses.
I am not sure what kind of tip you are looking for. An important step when using faces from _the wild_ is getting a good crop (face position and ratio).

**Comment by kenoharada** [comment]
Thank you for quick response!

I will try getting a good crop:+1:
